name: pr
on:
  pull_request:
    types:
      - edited
jobs:
  trigger-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check the PR body change
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          node ./src/pr
